### ISSUE TITLE
Question about value passed out into array

### ISSUE THREAD

**Issue by jtryan** [udacity/udacidrone#35]
This piece of code is returning self.q3 in an array and the other values are self._q<#>.
Shouldn't this be changed to self._q3?

https://github.com/udacity/udacidrone/blob/master/udacidrone/connection/message_types.py#L260-L263

```python
    @property
    def quaternions(self):
        """float array: numpy array of the quaternion vector """
        return np.array([self._q0, self._q1, self._q2, self.q3])

```

**Comment by domluna** [comment]
I've updated it to self._q3. In terms of correctness, it doesn't make a difference since we've defined the following methods https://github.com/udacity/udacidrone/blob/master/udacidrone/connection/message_types.py#L265-L283.

Nonetheless, It makes sense for them to be stylistically similar.
