### ISSUE TITLE
Connection to simulator closes during the computation after few minutes.

### ISSUE THREAD

**Issue by marufaytekin** [udacity/udacidrone#56]
Hi,

I am testing 3d Motion Planning assignment in Flying Car ND program. The connection to drone in the simulator seems closing while a program is executing path search. If the path search takes longer more than few minutes then tries to send waypoints to drone it sends `MessageID:CONENCTION_CLOSED` in on_message_receive() function in drone.py. Then it throws throws following exception: ```if (((msg.time - self._message_time) > 0.0)): AttributeError: 'int' object has no attribute 'time'```

Is there a keep alive setting for the connection that we can set? or is this a bug?

Thanks,
Maruf

**Comment by marufaytekin** [comment]
I just found out that we can set timeout for the connection: `Mavlink connection: conn = MavlinkConnection('tcp:{0}:{1}'.format(args.host, args.port), timeout=60)`

**Comment by RahilRehan** [comment]
But, How to solve the error?

**Comment by gillesvdp** [comment]
> But, How to solve the error?
The error can be solved by adding the timeout parameter
